import { z } from "zod";

export const mirrorSurfaceSchema = z.object({
  thought_process: z.array(z.string()).describe("List of sequential reasoning steps. Generate these FIRST."),
  surface_id: z.string(),
  
  // The spatial layout delta generated by this interaction
  new_nodes: z.array(
    z.object({
      id: z.string().describe("Unique ID for this node, e.g., 'artifact-1'"),
      type: z.enum([
        "artifact_node", "browser_node", "chart_node", "governance_node"
      ]),
      agent_id: z.enum(["MirrorGate", "Chetana", "MirrorBrain", "MirrorProof", "ActiveMirror"]).optional(),
      title: z.string(),
      body: z.string(),
      severity: z.enum(["info", "low", "medium", "high", "blocked"]).nullable(),
      metadata: z.any().nullable()
    })
  ).describe("New spatial widgets to spawn on the canvas."),
  
  new_edges: z.array(
    z.object({
      id: z.string(),
      source: z.string().describe("The ID of the source node (can be the user's chat message ID)"),
      target: z.string().describe("The ID of the target node being spawned"),
      label: z.string().nullable()
    })
  ).describe("Connections to draw between existing nodes and new nodes."),

  // Legacy fields retained for backwards compatibility or fallback logic
  suggested_prompts: z.array(z.string()),
});

export type MirrorSurfaceSpec = z.infer<typeof mirrorSurfaceSchema>;
